export const INDEX_CONFIG_TEMPLATE_NONE = 'none';
export const INDEX_CONFIG_TEMPLATE_BY_TYPE = 'byType';
export const INDEX_CONFIG_TEMPLATE_FULLTEXT = 'fulltext';
export const INDEX_CONFIG_TEMPLATE_PATH = 'path';
export const INDEX_CONFIG_TEMPLATE_MINIMAL = 'minimal';

export const INDEX_CONFIG_TEMPLATES = [
	INDEX_CONFIG_TEMPLATE_NONE,
	INDEX_CONFIG_TEMPLATE_BY_TYPE,
	INDEX_CONFIG_TEMPLATE_FULLTEXT,
	INDEX_CONFIG_TEMPLATE_PATH,
	INDEX_CONFIG_TEMPLATE_MINIMAL
] as const;
