export {
	INDEX_CONFIG_TEMPLATE_NONE,
	INDEX_CONFIG_TEMPLATE_BY_TYPE,
	INDEX_CONFIG_TEMPLATE_FULLTEXT,
	INDEX_CONFIG_TEMPLATE_PATH,
	INDEX_CONFIG_TEMPLATE_MINIMAL,
	INDEX_CONFIG_TEMPLATES
} from './constants';
export {enonify} from './enonify';
export {indexTemplateToConfig} from './indexTemplateToConfig';
export {
	dirname,
	join
} from './path';
export {
	STEMMING_LANGUAGE_CODE_ARABIC,
	STEMMING_LANGUAGE_CODE_BULGARIAN,
	STEMMING_LANGUAGE_CODE_BENGALI,
	STEMMING_LANGUAGE_CODE_CATALAN,
	STEMMING_LANGUAGE_CODE_CZECH,
	STEMMING_LANGUAGE_CODE_DANISH,
	STEMMING_LANGUAGE_CODE_GERMAN,
	STEMMING_LANGUAGE_CODE_GREEK,
	STEMMING_LANGUAGE_CODE_ENGLISH,
	STEMMING_LANGUAGE_CODE_BASQUE,
	STEMMING_LANGUAGE_CODE_PERSIAN,
	STEMMING_LANGUAGE_CODE_FINNISH,
	STEMMING_LANGUAGE_CODE_FRENCH,
	STEMMING_LANGUAGE_CODE_IRISH,
	STEMMING_LANGUAGE_CODE_GALICIAN,
	STEMMING_LANGUAGE_CODE_HINDI,
	STEMMING_LANGUAGE_CODE_HUNGARIAN,
	STEMMING_LANGUAGE_CODE_ARMENIAN,
	STEMMING_LANGUAGE_CODE_INDONESIAN,
	STEMMING_LANGUAGE_CODE_ITALIAN,
	STEMMING_LANGUAGE_CODE_JAPANESE,
	STEMMING_LANGUAGE_CODE_KOREAN,
	STEMMING_LANGUAGE_CODE_SORANI,
	STEMMING_LANGUAGE_CODE_LITHUANIAN,
	STEMMING_LANGUAGE_CODE_LATVIAN,
	STEMMING_LANGUAGE_CODE_DUTCH,
	STEMMING_LANGUAGE_CODE_NORWEGIAN,
	STEMMING_LANGUAGE_CODE_PORTUGUESE,
	STEMMING_LANGUAGE_CODE_BRAZILIAN,
	STEMMING_LANGUAGE_CODE_ROMANIAN,
	STEMMING_LANGUAGE_CODE_RUSSIAN,
	STEMMING_LANGUAGE_CODE_SPANISH,
	STEMMING_LANGUAGE_CODE_SWEDISH,
	STEMMING_LANGUAGE_CODE_TURKISH,
	STEMMING_LANGUAGE_CODE_THAI,
	STEMMING_LANGUAGE_CODE_CHINESE,
	STEMMING_LANGUAGE_CODES,
	STEMMING_LANGUAGES
} from './stemming';
export {updateIndexConfigs} from './updateIndexConfigs';
export {
	VALUE_TYPE_ANY,
	VALUE_TYPE_BOOLEAN,
	VALUE_TYPE_DOUBLE,
	VALUE_TYPE_GEO_POINT,
	VALUE_TYPE_INSTANT,
	VALUE_TYPE_LOCAL_DATE,
	VALUE_TYPE_LOCAL_DATE_TIME,
	VALUE_TYPE_LOCAL_TIME,
	VALUE_TYPE_LONG,
	VALUE_TYPE_REFERENCE,
	VALUE_TYPE_SET,
	VALUE_TYPE_STRING
} from './valueType';
