interface Language {
	code:string,
	language:string
}

// https://developer.enonic.com/docs/xp/stable/storage/indexing#languages
export const LANGUAGES:Array<Language> = [
	{
		code: 'ar',
		language: 'Arabic'
	}, {
		code: 'bg',
		language: 'Bulgarian'
	}, {
		code: 'bn',
		language: 'Bengali'
	}, {
		code: 'ca',
		language: 'Catalan'
	}, {
		code: 'cs',
		language: 'Czech'
	}, {
		code: 'da',
		language: 'Danish'
	}, {
		code: 'de',
		language: 'German'
	}, {
		code: 'el',
		language: 'Greek'
	}, {
		code: 'en',
		language: 'English'
	}, {
		code: 'eu',
		language: 'Basque'
	}, {
		code: 'fa',
		language: 'Persian'
	}, {
		code: 'fi',
		language: 'Finnish'
	}, {
		code: 'fr',
		language: 'French'
	}, {
		code: 'ga',
		language: 'Irish'
	}, {
		code: 'gl',
		language: 'Galician'
	}, {
		code: 'hi',
		language: 'Hindi'
	}, {
		code: 'hu',
		language: 'Hungarian'
	}, {
		code: 'hy',
		language: 'Armenian'
	}, {
		code: 'id',
		language: 'Indonesian'
	}, {
		code: 'it',
		language: 'Italian'
	}, {
		code: 'ja',
		language: 'Japanese'
	}, {
		code: 'ko',
		language: 'Korean'
	}, {
		code: 'ku',
		language: 'Sorani'
	}, {
		code: 'lt',
		language: 'Lithuanian'
	}, {
		code: 'lv',
		language: 'Latvian'
	}, {
		code: 'nl',
		language: 'Dutch'
	}, {
		code: 'no',
		language: 'Norwegian'
	}, {
		code: 'pt',
		language: 'Portuguese'
	}, {
		code: 'pt-br',
		language: 'Brazilian'
	}, {
		code: 'ro',
		language: 'Romanian'
	}, {
		code: 'ru',
		language: 'Russian'
	}, {
		code: 'es',
		language: 'Spanish'
	}, {
		code: 'sv',
		language: 'Swedish'
	}, {
		code: 'tr',
		language: 'Turkish'
	}, {
		code: 'th',
		language: 'Thai'
	}, {
		code: 'zh',
		language: 'Chinese'
	}
];
