export const HTTP_REQUEST_MODE_EDIT = 'edit';
export const HTTP_REQUEST_MODE_INLINE = 'inline';
export const HTTP_REQUEST_MODE_LIVE = 'live';
export const HTTP_REQUEST_MODE_PREVIEW = 'preview';
export const HTTP_REQUEST_MODES = [
	HTTP_REQUEST_MODE_EDIT,
	HTTP_REQUEST_MODE_INLINE,
	HTTP_REQUEST_MODE_LIVE,
	HTTP_REQUEST_MODE_PREVIEW
];
