export {
	LANGUAGES,
	QUERY_FUNCTION_FULLTEXT,
	QUERY_FUNCTION_NGRAM,
	QUERY_FUNCTION_RANGE,
	QUERY_FUNCTION_PATH_MATCH,
	QUERY_FUNCTION_STEMMED,
	VALUE_TYPE_ANY,
	VALUE_TYPE_BOOLEAN,
	VALUE_TYPE_GEO_POINT,
	VALUE_TYPE_INSTANT,
	VALUE_TYPE_LOCAL_DATE,
	VALUE_TYPE_LOCAL_DATE_TIME,
	VALUE_TYPE_LOCAL_TIME,
	VALUE_TYPE_SET,
	VALUE_TYPE_STRING
} from './storage';
